version: "3.8"

volumes:
  peer0.org1.hypctt.com:
  peer1.org1.hypctt.com:
  # peer2.org1.hypctt.com:
  # peer3.org1.hypctt.com:

networks:
  hypcttnetwork:
    driver: bridge

services:
  peer0.org1.hypctt.com:
    hostname: peer0.org1.hypctt.com
    container_name: peer0.org1.hypctt.com
    image: hyperledger/fabric-peer:2.5.9
    restart: always
    environment:
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

      # PEER ENV
      - CORE_PEER_ID=peer0.org1.hypctt.com
      - CORE_PEER_ADDRESS=peer0.org1.hypctt.com:7061
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_LOGLEVEL=DEBUG
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.hypctt.com:7062
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7062
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.hypctt.com:7061
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.hypctt.com:7061
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false

      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org1.hypctt.com:9444
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hypcttnetwork
      - FABRIC_LOGGING_SPEC=INFO

      # CouchDb
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.org1.hypctt.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=rootuser
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pwd9012

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    depends_on:
      - couchdb.peer0.org1
    volumes:
      - /var/run/:/host/var/run/
      - ../../crypto-config/peerOrganizations/org1.hypctt.com/peers/peer0.org1.hypctt.com/msp:/etc/hyperledger/fabric/msp
      - ../../crypto-config/peerOrganizations/org1.hypctt.com/peers/peer0.org1.hypctt.com/tls:/etc/hyperledger/fabric/tls
      - peer0.org1.hypctt.com:/var/hyperledger/production
    ports:
      - 7061:7061
      - 7062:7062
      - 9444:9444
    networks:
      - hypcttnetwork

  couchdb.peer0.org1:
    container_name: couchdb.peer0.org1
    hostname: couchdb.peer0.org1.hypctt.com
    image: couchdb:3.3.3
    restart: always
    environment:
      - COUCHDB_USER=rootuser
      - COUCHDB_PASSWORD=pwd9012
    ports:
      - 5984:5984
    networks:
      - hypcttnetwork

  peer1.org1.hypctt.com:
    hostname: peer1.org1.hypctt.com
    container_name: peer1.org1.hypctt.com
    image: hyperledger/fabric-peer:2.5.9
    restart: always
    environment:
      # TLS
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt

      # PEER ENV
      - CORE_PEER_ID=peer1.org1.hypctt.com
      - CORE_PEER_ADDRESS=peer1.org1.hypctt.com:7071
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_LOGLEVEL=DEBUG
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.hypctt.com:7072
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7072
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.hypctt.com:7071
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.hypctt.com:7071
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false

      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_OPERATIONS_LISTENADDRESS=peer1.org1.hypctt.com:9445
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1org1"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hypcttnetwork
      - FABRIC_LOGGING_SPEC=INFO

      # CouchDb
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer1.org1.hypctt.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=rootuser123
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=pwd9012

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    depends_on:
      - couchdb.peer1.org1
    volumes:
      - /var/run/:/host/var/run/
      - ../../crypto-config/peerOrganizations/org1.hypctt.com/peers/peer1.org1.hypctt.com/msp:/etc/hyperledger/fabric/msp
      - ../../crypto-config/peerOrganizations/org1.hypctt.com/peers/peer1.org1.hypctt.com/tls:/etc/hyperledger/fabric/tls
      - peer1.org1.hypctt.com:/var/hyperledger/production
    ports:
      - 7071:7071
      - 7072:7072
      - 9445:9445
    networks:
      - hypcttnetwork

  couchdb.peer1.org1:
    container_name: couchdb.peer1.org1
    hostname: couchdb.peer1.org1.hypctt.com
    image: couchdb:3.3.3
    restart: always
    environment:
      - COUCHDB_USER=rootuser123
      - COUCHDB_PASSWORD=pwd9012
    ports:
      - "6984:5984"
    networks:
      - hypcttnetwork
