OrdererOrgs:
  - Name: OrdererOrg
    Domain: hypctt.com
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3

PeerOrgs:
  - Name: org1
    Domain: org1.hypctt.com
    EnableNodeOUs: true
    Template:
      Count: 4
    Users:
      Count: 3

  - Name: org2
    Domain: org2.hypctt.com
    EnableNodeOUs: true
    Template:
      Count: 4
    Users:
      Count: 3
