version: "3.8"

networks:
  hypcttnetwork:
    driver: bridge

services:
  ca-peer-org2:
    hostname: ca-peer-org2.hypctt.com
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-peer-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7032
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../../fabric-ca/peerOrg/hypctt.com/org2:/etc/hyperledger/fabric-ca-server
    container_name: ca-peer-org2
    ports:
      - "7032:7032"
    networks:
      - hypcttnetwork
