version: "3.8"

networks:
  hypcttnetwork:
    driver: bridge

services:
  cliorg1:
    container_name: cliorg1
    image: hyperledger/fabric-tools:2.5.9
    tty: true
    stdin_open: true
    restart: on-failure
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # Peer Init
      - CORE_PEER_ID=peer0.org1.hypctt.com
      - CORE_PEER_ADDRESS=peer0.org1.hypctt.com:7061
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/crypto/peerOrganizations/org1.hypctt.com/users/Admin@org1.hypctt.com/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/crypto/peerOrganizations/org1.hypctt.com/peers/peer0.org1.hypctt.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/crypto/peerOrganizations/org1.hypctt.com/peers/peer0.org1.hypctt.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/crypto/peerOrganizations/org1.hypctt.com/peers/peer0.org1.hypctt.com/tls/ca.crt
      - CORE_CHAINCODE_MODE=dev
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/crypto/ordererOrganizations/hypctt.com/orderers/orderer1.hypctt.com/tls/ca.crt
      - ADMIN_CERT=/opt/gopath/src/github.com/hyperledger/fabric/crypto/ordererOrganizations/hypctt.com/users/Admin@hypctt.com/tls/client.crt
      - ADMIN_KEY=/opt/gopath/src/github.com/hyperledger/fabric/crypto/ordererOrganizations/hypctt.com/users/Admin@hypctt.com/tls/client.key
      - ORDERER_ADDRESS=orderer1.hypctt.com:7040
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
      - /var/run/:/host/var/run/
      - ../../../smart-contract:/opt/gopath/src/github.com/chaincode
      - ../../../crypto-config/peerOrganizations:/opt/gopath/src/github.com/hyperledger/fabric/crypto/peerOrganizations
      - ../../../crypto-config/ordererOrganizations:/opt/gopath/src/github.com/hyperledger/fabric/crypto/ordererOrganizations
      - ../../../channel-artifacts/org1:/opt/gopath/src/github.com/hyperledger/fabric/channel-artifacts
    networks:
      - hypcttnetwork
