version: "3.8"

volumes:
  orderer1.hypctt.com:

networks:
  hypcttnetwork:
    driver: bridge

services:
  orderer1.hypctt.com:
    hostname: orderer1.hypctt.com
    container_name: orderer1.hypctt.com
    image: hyperledger/fabric-orderer:2.5.9
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7040
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_GENERAL_BOOTSRAPFILE=""
      - ORDERER_GENERAL_ORDERERTYPE=etcdraft
      # TLS SETTING
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=/var/hyperledger/orderer/tls/ca.crt
      # Cluster Setting
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=/var/hyperledger/orderer/tls/ca.crt
      # Admin Setting
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7050
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=/var/hyperledger/orderer/admin/tls/ca.crt
      - ORDERER_ADMIN_TLS_CLIENT_AUTH_REQUIRED=true
      - ORDERER_CHANNEL_PARTICIPATION_ENABLED=true

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../../crypto-config/ordererOrganizations/hypctt.com/orderers/orderer1.hypctt.com/msp:/var/hyperledger/orderer/msp
      - ../../crypto-config/ordererOrganizations/hypctt.com/orderers/orderer1.hypctt.com/tls:/var/hyperledger/orderer/tls
      - ../../crypto-config/ordererOrganizations/hypctt.com/users/Admin@hypctt.com:/var/hyperledger/orderer/admin
      - orderer1.hypctt.com:/var/hyperledger/production/orderer
    ports:
      - 7040:7040
      - 7050:7050
    networks:
      - hypcttnetwork
